plugins {
    id 'java-library'
    alias(libs.plugins.spring.dep.mgmt)
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.boot:spring-boot-dependencies:${libs.versions.spring.boot.get()}"
    }
}

dependencies {
    api project(':core:core-domain')
    api project(':core:core-plugin-sdk')

    implementation 'org.springframework:spring-context'
    implementation 'org.springframework:spring-tx'
    implementation 'org.springframework.boot:spring-boot'
    implementation 'org.springframework.boot:spring-boot-autoconfigure'
    implementation 'jakarta.annotation:jakarta.annotation-api'
    implementation 'tools.jackson.core:jackson-databind'
    implementation libs.cron.utils
    implementation libs.guava           
    implementation libs.slf4j.api

    testImplementation libs.junit.jupiter
    testImplementation libs.assertj.core
    
    testImplementation project(':core:core-plugin-builtin')
    
    testRuntimeOnly libs.junit.platform.launcher
}
