[versions]
java = "26"
spring-boot = "4.0.6"
spring-dep-mgmt = "1.1.7"
postgresql = "42.7.4"

flyway = "11.14.1"
hypersistence-utils = "3.15.2"
pebble = "3.2.2"
cron-utils = "9.2.1"
testcontainers = "1.20.3"
assertj = "3.26.3"
junit = "6.0.3"
junit-platform = "6.0.3"
slf4j = "2.0.16"
archunit = "1.4.1"
awaitility = "4.2.2"
guava = "33.4.0-jre"

[libraries]
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-postgres = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }
hypersistence-utils = { module = "io.hypersistence:hypersistence-utils-hibernate-73", version.ref = "hypersistence-utils" }
pebble = { module = "io.pebbletemplates:pebble", version.ref = "pebble" }
cron-utils = { module = "com.cronutils:cron-utils", version.ref = "cron-utils" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
testcontainers-postgres = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }
testcontainers-junit = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }
archunit-junit5 = { module = "com.tngtech.archunit:archunit-junit5", version.ref = "archunit" }
awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitility" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dep-mgmt = { id = "io.spring.dependency-management", version.ref = "spring-dep-mgmt" }
